controllers:
  cancel_play: &cancel_play 0
  start_stop_recording: &start_stop_recording 2
  play_temp: &play_temp 3
  del_temp: &del_temp 4
  append_temp_to_bank: &append_temp_to_bank 5
  play_bank: &play_bank 6
  save_bank: &save_bank 7
  restart_recording: &restart_recording 8
  del_bank: &del_bank 9
  reset_step_index: &reset_step_index 10
  step_next: &step_next 11
  step_previous: &step_previous 12
  load_bank_to_step: &load_bank_to_step 13
  bank_select: &bank_select 16
  filter_chords_jump: &filter_chords_jump 17
  filter_chords_ignore: &filter_chords_ignore 18
  record_taps: &record_taps 19
  delete_step: &delete_step 20
  incremental_add: &incremental_add 21
  multi_step: &multi_step 22
  sustain_pedal: &sustain_pedal 64
  transpose_up: &transpose_up 23
  transpose_down: &transpose_down 24

channels:
  recorder_output: 0
  ping: 8
  piano_output: 0

keymap:
# controllers
  27:
    # cancel play
    control: true
    param: *cancel_play
    hold: true
  30:
    control: true
    param: *step_next
    value: 64
    hold: false
  4:
    control: true
    param: *step_previous
    value: 64
    hold: false
  7:
    control: true
    param: *sustain_pedal
    value: 64
    hold: true

  28:
    control: true
    param: *reset_step_index
    value: 64
    hold: true

  31:
    control: true
    param: *restart_recording
    hold: true
    value: 64
  32:
    control: true
    param: *start_stop_recording
    hold: true
    value: 64

  33: # play tmp
    control: true
    param: *play_temp
    hold: true
    value: 64
  34: # reset tmp
    control: true
    param: *del_temp
    hold: true
    value: 64
  35: # append tmp
    control: true
    param: *append_temp_to_bank
    hold: true
    value: 64
  36: # play main
    control: true
    hold: true
    param: *play_bank
    value: 64
  37: # delete main
    value: 64
    hold: true
    control: true
    param: 9
  38: # save main
    control: true
    param: *save_bank
    hold: true
    value: 64
  42:
    control: true
    param: *load_bank_to_step
    hold: true

# banks
# for i in {1..12}; do echo "$(( 96 + $i)): {control: true, param: 16, value: $i, hold: false}"; done|yq -P|sed 's/^/  /g'
  97:
    control: true
    param: *bank_select
    value: 1
    hold: false
  98:
    control: true
    param: *bank_select
    value: 2
    hold: false
  99:
    control: true
    param: *bank_select
    value: 3
    hold: false
  100:
    control: true
    param: *bank_select
    value: 4
    hold: false
  101:
    control: true
    param: *bank_select
    value: 5
    hold: false
  102:
    control: true
    param: *bank_select
    value: 6
    hold: false
  103:
    control: true
    param: *bank_select
    value: 7
    hold: false
  104:
    control: true
    param: *bank_select
    value: 8
    hold: false
  105:
    control: true
    param: *bank_select
    value: 9
    hold: false
  106:
    control: true
    param: *bank_select
    value: 10
    hold: false
  107:
    control: true
    param: *bank_select
    value: 11
    hold: false
  108:
    control: true
    param: *bank_select
    value: 12
    hold: false

  25: # inser: filter1
    control: true
    param: *filter_chords_jump
    hold: true
  26: # suppr: filter2
    control: true
    param: *filter_chords_ignore
    hold: true
  131: # affichage: record debugger into temp
    control: true
    param: *record_taps
    hold: true
    value: 64
  2: # arret defil: delete previous note in temp_recording
    control: true
    hold: false
    param: *delete_step
  10: # alt: include previous note in incremental buffer
    control: true
    hold: true
    param: *incremental_add
  29:
    control: true
    hold: false
    param: *multi_step
    value: 64
  44: # numpad +
    control: true
    hold: true
    param: *transpose_up
    value: 64
  45: # numpad +
    control: true
    hold: true
    param: *transpose_down
    value: 64
# notes
  3:
    value: 147
  48:
    value: 92
  50:
    value: 78
  51:
    value: 80
  52:
    value: 82
  54:
    value: 85
  55:
    value: 87
  57:
    value: 90
  58:
    value: 78
  59:
    value: 74
  60:
    value: 94
  61:
    value: 76
  62:
    value: 77
  64:
    value: 64
  65:
    value: 61
  66:
    value: 69
  67:
    value: 65
  69:
    value: 81
  70:
    value: 66
  71:
    value: 68
  72:
    value: 70
  73:
    value: 89
  75:
    value: 73
  76:
    value: 75
  77:
    value: 72
  78:
    value: 71
  79:
    value: 91
  80:
    value: 93
  81:
    value: 77
  82:
    value: 83
  83:
    value: 63
  84:
    value: 84
  85:
    value: 88
  86:
    value: 67
  87:
    value: 79
  88:
    value: 64
  89:
    value: 86
  90:
    value: 62
  93:
    value: 95
  94:
    value: 96
  95:
    value: 96
  139:
    value: 60
  6: 
    value: 59
