// Code generated by "stringer -type=DemiTon"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[bémol - -1]
	_ = x[dièse-1]
}

const (
	_DemiTon_name_0 = "bémol"
	_DemiTon_name_1 = "dièse"
)

func (i DemiTon) String() string {
	switch {
	case i == -1:
		return _DemiTon_name_0
	case i == 1:
		return _DemiTon_name_1
	default:
		return "DemiTon(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
