// Code generated by "stringer -type=Note"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SiDièse-0]
	_ = x[Do-0]
	_ = x[DoDièse-1]
	_ = x[RéBémol-1]
	_ = x[Ré-2]
	_ = x[RéDièse-3]
	_ = x[MiBémol-3]
	_ = x[Mi-4]
	_ = x[Fa-5]
	_ = x[FaDièse-6]
	_ = x[SolBémol-6]
	_ = x[Sol-7]
	_ = x[SolDièse-8]
	_ = x[LaBémol-8]
	_ = x[La-9]
	_ = x[SiBémol-10]
	_ = x[Si-11]
	_ = x[DoBémol-11]
}

const _Note_name = "SiDièseDoDièseRéRéDièseMiFaFaDièseSolSolDièseLaSiBémolSi"

var _Note_index = [...]uint8{0, 8, 16, 19, 28, 30, 32, 40, 43, 52, 54, 62, 64}

func (i Note) String() string {
	if i < 0 || i >= Note(len(_Note_index)-1) {
		return "Note(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Note_name[_Note_index[i]:_Note_index[i+1]]
}
